# Generated by Django 3.0.7 on 2020-12-04 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_form_model',
            fields=[
                ('U_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.CharField(max_length=100)),
                ('Message', models.TextField(max_length=1000)),
                ('Date', models.CharField(max_length=100)),
                ('File_status', models.IntegerField()),
            ],
            options={
                'db_table': 'Contact_us',
            },
        ),
        migrations.CreateModel(
            name='File_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(blank=True, null=True, upload_to='media/')),
                ('U', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Contact_form_model')),
            ],
            options={
                'db_table': 'Files',
            },
        ),
    ]
